import { useEffect, useState } from 'react';
import { LanguageContext } from './language-context';

const translations = {
    en: {
        settings: 'Settings',
        appearance: 'Appearance',
        language: 'Language',
        profile: 'Profile',
        security: 'Security',
        dataRetention: 'Data Retention',
        retentionHint: 'Auto cleanup runs monthly: deletes logs and processed requests older than these days.',
        logsRetentionDays: 'Log retention (days)',
        requestsRetentionDays: 'Message retention (days)',
        lastCleanupAt: 'Last cleanup',
        nextCleanupAt: 'Next cleanup',
        runCleanupNow: 'Run cleanup now',
        retentionLoadFailed: 'Failed to load retention settings',
        retentionCleanupFailed: 'Cleanup failed',
        passwordMismatch: 'Passwords do not match',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
        changeAvatar: 'Change Avatar',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        saveChanges: 'Save',
        dashboard: 'Dashboard',
        devices: 'Devices',
        booking: 'Booking',
        messages: 'Messages',
        chinese: 'Chinese',
        english: 'English',
        inventory: 'Inventory Entry',
        requestModification: 'Request Modification',
        contactAdmin: 'Please contact an administrator to modify this item.',
        quantity: 'Quantity',
        actions: 'Actions',
        addItem: 'Add Item',
        edit: 'Edit',
        cancel: 'Cancel',
        category: 'Category',
        itemName: 'Item Name',
        applicant: 'Applicant',
        inventoryList: 'Inventory List',
        date: 'Date',
        status: 'Status',
        reviewing: 'Reviewing',
        rejected: 'Rejected',
        approved: 'Approved',
        exampleItemName: 'e.g. iPhone 15',
        exampleCategory: 'e.g. Electronics',
        welcomeBack: 'Welcome back',
        upcomingReservations: 'Upcoming Reservations',
        reservedHours: 'Reserved Hours',
        hours: 'Hours',
        completed: 'Completed',
        recentActivity: 'Recent Activity',
        noActivity: 'No recent activity',
        systemUser: 'System',
        loginParams: 'User logged in',
        createDevice: 'Create Device',
        createReservation: 'Create Reservation',
        registerUser: 'User Registered',
        logout: 'Logout',
        super_admin: 'Super Admin',
        admin: 'Admin',
        user: 'User',
        SUPER_ADMIN: 'Super Admin',
        ADMIN: 'Admin',
        USER: 'User',
        displayName: 'Display Name',
        updateSuccess: 'Update Successful',
        login: 'Log in',
        signup: 'Sign up',
        confirmClearLogs: 'Are you sure you want to clear all logs?',
        clearLogsFailed: 'Failed to clear logs',
        searchLogs: 'Search logs...',
        clearLogs: 'Clear logs',
        docsTitle: 'Appointer Docs',
        docsDescription: 'Learn how to make the most of Appointer. This page will contain documentation and guides about booking devices, managing reservations, and getting the best out of the system.',
        deviceList: 'Device List',
        selectDeviceToBook: 'Select a device to book',
        updateFailed: 'Update failed, please try again',
        deleteFailed: 'Delete failed, please try again',
        createDeviceSuccess: 'Device created successfully',
        createDeviceFailed: 'Failed to create device, please try again',
        newDevice: 'New Device',
        mon: 'Mon',
        tue: 'Tue',
        wed: 'Wed',
        thu: 'Thu',
        fri: 'Fri',
        sat: 'Sat',
        sun: 'Sun',
        bookNow: 'Book Now',
        delete: 'Delete',
        confirm: 'Confirm',
        deleteDevice: 'Delete Device',
        enterDeviceName: 'Enter device name',
        addDescription: 'Add description...',
        doubleClickInfo: 'Double click to edit',
        available: 'Available',
        unavailable: 'Unavailable',
        on: 'On',
        off: 'Off',
        week: '',
        commit: 'Commit',
        user_management: 'User Management',
        user_management_subtitle: 'Manage system users and access controls.',
        search_users: 'Search users...',
        expiry_date: 'Expiry Date',
        permanent: 'Permanent',
        leaderboard: 'Leaderboard',
        leaderboard_subtitle: 'Top contributors by total reservation hours. Keep up the good work!',
        rank: 'Rank',
        column_user: 'User',
        role: 'Role',
        total_duration: 'Total Duration',
        edit_user: 'Edit User',
        delete_user_confirm: 'Are you sure you want to delete this user?'
    },
    zh: {
        settings: '设置',
        appearance: '外观',
        language: '语言',
        profile: '个人资料',
        security: '账号安全',
        dataRetention: '数据保留',
        retentionHint: '系统每月自动清理：删除超过以下天数的日志和已处理申请。',
        logsRetentionDays: '日志保留天数',
        requestsRetentionDays: '消息保留天数',
        lastCleanupAt: '上次清理时间',
        nextCleanupAt: '下次计划清理时间',
        runCleanupNow: '立即执行清理',
        retentionLoadFailed: '加载保留策略失败',
        retentionCleanupFailed: '执行清理失败',
        passwordMismatch: '两次输入的密码不一致',
        light: '浅色',
        dark: '深色',
        system: '跟随系统',
        changeAvatar: '更换头像',
        changePassword: '修改密码',
        currentPassword: '当前密码',
        newPassword: '新密码',
        confirmPassword: '确认密码',
        saveChanges: '保存',
        dashboard: '仪表盘',
        devices: '设备管理',
        booking: '设备预约',
        messages: '消息通知',
        chinese: '中文',
        english: 'English',
        inventory: '入库单',
        requestModification: '申请修改',
        contactAdmin: '请联系管理员修改此条目。',
        quantity: '数量',
        actions: '操作',
        addItem: '添加入库',
        edit: '编辑',
        cancel: '取消',
        category: '类别',
        itemName: '入库项',
        applicant: '申请人',
        inventoryList: '入库单',
        date: '日期',
        status: '状态',
        reviewing: '审核中',
        rejected: '已拒绝',
        approved: '已通过',
        exampleItemName: '例如：iPhone 15',
        exampleCategory: '例如：电子产品',
        welcomeBack: '欢迎回来',
        upcomingReservations: '即将到来的预约',
        reservedHours: '已预约时长',
        hours: '小时',
        completed: '已完成',
        recentActivity: '最近活动',
        noActivity: '暂无最近活动',
        systemUser: '系统',
        loginParams: '登录系统',
        createDevice: '创建设备',
        createReservation: '创建预约',
        registerUser: '新用户注册',
        logout: '退出登录',
        super_admin: '超级管理员',
        admin: '管理员',
        user: '普通用户',
        SUPER_ADMIN: '超级管理员',
        ADMIN: '管理员',
        USER: '普通用户',
        displayName: '显示名称',
        updateSuccess: '更新成功',
        login: '登录',
        signup: '注册',
        confirmClearLogs: '您确定要清空所有日志记录吗？',
        clearLogsFailed: '清空日志失败',
        searchLogs: '搜索日志...',
        clearLogs: '清空日志',
        docsTitle: 'Appointer 文档',
        docsDescription: '了解如何充分利用 Appointer。本页面包含有关设备预约、管理预约以及如何最大限度利用系统的文档和指南。',
        deviceList: '设备列表',
        selectDeviceToBook: '选择设备进行预约',
        updateFailed: '更新失败，请重试',
        deleteFailed: '删除失败，请重试',
        createDeviceSuccess: '设备创建成功',
        createDeviceFailed: '创建设备失败，请重试',
        newDevice: '新设备',
        mon: '一',
        tue: '二',
        wed: '三',
        thu: '四',
        fri: '五',
        sat: '六',
        sun: '日',
        bookNow: '立即预约',
        delete: '删除',
        confirm: '确认',
        deleteDevice: '删除设备',
        enterDeviceName: '输入设备名称',
        addDescription: '添加描述...',
        doubleClickInfo: '双击编辑',
        available: '可用',
        unavailable: '不可用',
        on: '开',
        off: '关',
        week: '周',
        commit: '提交',
        user_management: '用户管理',
        user_management_subtitle: '管理系统用户和访问权限。',
        search_users: '搜索用户...',
        expiry_date: '有效期至',
        permanent: '永久有效',
        leaderboard: '排行榜',
        leaderboard_subtitle: '按总预约时长排名的贡献者。继续保持！',
        rank: '排名',
        column_user: '用户',
        role: '角色',
        total_duration: '总时长',
        edit_user: '编辑用户',
        delete_user_confirm: '您确定要删除此用户吗？'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        try {
            return localStorage.getItem('drms_language') || 'zh';
        } catch {
            return 'zh';
        }
    });

    useEffect(() => {
        try {
            localStorage.setItem('drms_language', language);
        } catch {
            // ignore storage failures
        }
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
